variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

.java-sdk-base:
  cache:
    paths:
     - .m2/repository/
      - target/
  before_script:
    - yum update
    - yum install gnupg
    - cd packages/pangea-sdk
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.java-sdk-publish:
  cache:
    paths:
      - .m2/repository/
      - target/
  before_script:
    - cd packages/pangea-sdk
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
      changes:
        - packages/pangea-sdk/**/*
      when: on_success

building_sdk:
  extends: .java-sdk-base
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

testing_sdk:
  extends: .java-sdk-base
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

publishing_sdk:
  extends: .java-sdk-publish
  stage: publish
  script:
    - mvn $MAVEN_CLI_OPTS deploy
