.java-sdk-base
  cache:
    paths:
      - target/
  before_script:
    - cd packages/pangea-sdk
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

build:
  extends: .java-sdk-base
  stage: build
  script:
    - mvn compile

test:
  extends: .java-sdk-base
  stage: test
  script:
    - mvn test
