.java-sdk-base
  cache:
    paths:
      - target/
  before_script:
    - cd packages/pangea-sdk
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - packages/pangea-sdk/**/*
      when: on_success

build:
  extends: .java-sdk-base
  stage: build
  script:
    - mvn compile

test:
  extends: .java-sdk-base
  stage: test
  script:
    - mvn test
