variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

.jsondoclet-base:
  before_script:
    - cd packages/jsondoclet
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.jsondoclet-publish:
  before_script:
    - cd packages/jsondoclet
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
      changes:
        - packages/jsondoclet/**/*
      when: on_success

building_jsondoclet:
  extends: .jsondoclet-base
  stage: build
  script:
    - mvn compile

testing_jsondoclet:
  extends: .jsondoclet-base
  stage: test
  script:
    - mvn test

publishing_jsondoclet:
  extends: .jsondoclet-publish
  stage: publish
  script:
    - mvn deploy
